### ISSUE TITLE
ローディング画面のロジック

### ISSUE THREAD

**Issue by tanacchi** [jphacks/FK_1906#4]
草案 1.
```html
<p id="loading_state" onChanged="some_func()">STATE</p>
```
STATEには，
* READY (まだ動画がアップされていない)
* LOADING (ローディング中)
* DONE(ロード終了)

PythonがSTATEを書き換える．
書き換わったタイミングで(onChanged)，js の some_func が呼ばれ，
some_func は，STATE の中身で挙動を変える
ex.
READY => 何もしない．
LODING => わたるを回転させる．
DONE => わたるを消す．

**Comment by syu-kwsk** [comment]
解決しました
